### ISSUE TITLE
How do I use it? any tutorials please?

### ISSUE THREAD

**Issue by shonilchi** [htadashi/GPT3-AHK#1]

**Comment by shonilchi** [comment]
What's the API Key that it's asking me?

**Comment by htadashi** [comment]
Hi @shonilchi, you should create an account in [OpenAI](https://beta.openai.com/overview) website and create a new API key in this [link](https://beta.openai.com/account/api-keys).

**Comment by htadashi** [comment]
Improve the README.md with clearer instructions
