### ISSUE TITLE
Support for Azure OpenAI API

### ISSUE THREAD

**Issue by lchyn** [htadashi/GPT3-AHK#12]
Hello，
Currently this AHK code can only work under the official OPENAI API;
Could you please add support for OPENAI service in Microsoft AZURE?
What about making the code work properly under the Azure OPENAI API
 (https://learn.microsoft.com/en-us/azure/ai-services/openai/reference)?

Thanks！

**Comment by htadashi** [comment]
Hi @lchyn and @ishaan-jaff.

Thanks for opening the issue. I followed @ishaan-jaff suggestion and added an option to call custom models compatible with OpenAI API standard in https://github.com/htadashi/GPT3-AHK/commit/c7de601d7417180d851190080048ba40ad6f74e5

In particular, you can run the [litellm](https://github.com/BerriAI/litellm) server in your computer following the [quickstart instructions](https://docs.litellm.ai/docs/proxy/quick_start), and setup the `CUSTOM_MODEL_ENDPOINT` and `CUSTOM_MODEL_ID` to respectively point out to your server IP and to your desired [Azure model name](https://docs.litellm.ai/docs/providers/azure).
