### ISSUE TITLE
Polish char coding

### ISSUE THREAD

**Issue by kinpio** [htadashi/GPT3-AHK#2]
Encoding of Polish characters did not work.  In place of Polish characters, incomprehensible letters appear

**Comment by htadashi** [comment]
Hi Kinpio, thanks for reporting the issue. Could you give me some examples of prompts that you used so I can use them to test some potential fixes?

**Comment by kinpio** [comment]
Hi,

just type "polish alphabet" and use Win+O.

"
A, �?, B, C, �?, D, E, Ę, F, G, H, I, J, K, L, ?�, M, N, ?�, O, ??, P, R,
S, ??, T, U, W, Y, Z, ??, ?�
"

it should look like:
"
A, Ą, B, C, Ć, D, E, Ę, F, G, H, I, J, K, L, Ł, M, N, Ń, O, Ó, P, R, S, Ś,
T, U, W, Y, Z, Ż, Ź
"

-- 
Piotr

Niniejsza korespondencja przeznaczona jest wyłącznie dla osoby lub
podmiotu, do którego jest zaadresowana i może zawierać treści chronione
przepisami prawa. Wgląd w treść wiadomości otrzymanej omyłkowo, dalsze jej
przekazywanie, rozpowszechnianie lub innego rodzaju wykorzystanie, bądź
podjęcie jakichkolwiek działań w oparciu o zawarte w niej informacje przez
osobę lub podmiot nie będący adresatem, jest niedozwolone. Odbiorca
korespondencji, który otrzymał ją omyłkowo, proszony jest o zawiadomienie
nadawcy i usunięcie tego materiału z komputera.



niedz., 5 lut 2023 o 11:17 Tadashi ***@***.***> napisał(a):

**Comment by htadashi** [comment]
Hi @kinpio. https://github.com/htadashi/GPT3-AHK/commit/896feb88df5ebcb53a12da2045963f0a46e76ae8 seems to fix the issue.

**Comment by kinpio** [comment]
I confirm, issue is a thing of the past

Piotr
-- 
Piotr

Niniejsza korespondencja przeznaczona jest wyłącznie dla osoby lub
podmiotu, do którego jest zaadresowana i może zawierać treści chronione
przepisami prawa. Wgląd w treść wiadomości otrzymanej omyłkowo, dalsze jej
przekazywanie, rozpowszechnianie lub innego rodzaju wykorzystanie, bądź
podjęcie jakichkolwiek działań w oparciu o zawarte w niej informacje przez
osobę lub podmiot nie będący adresatem, jest niedozwolone. Odbiorca
korespondencji, który otrzymał ją omyłkowo, proszony jest o zawiadomienie
nadawcy i usunięcie tego materiału z komputera.



niedz., 5 lut 2023 o 18:57 Tadashi ***@***.***> napisał(a):
