### ISSUE TITLE
Version 0.2.0 stopped working

### ISSUE THREAD

**Issue by Avastgard** [htadashi/GPT3-AHK#5]
After upgrading do v. 0.2.0, the script stopped working. Pressing Win+o with the text selected simply pastes the text back and adds a space after it.

**Comment by qrcode-generator** [comment]
same here . Tried older version and same problem .The ahk error : Error in #include file .......lib\WinHttpRequest.ahk    0x80070057 wrong parameter Specifically :Option    . Line 044: this.whr.Option[9] :=0x2800 . Hope is helps to fix it .

**Comment by htadashi** [comment]
Thanks for the report. This happens only with the executable of the release versions or also when running [GPT3-AHK.ahk](https://github.com/htadashi/GPT3-AHK/blob/main/GPT3-AHK.ahk)?

**Comment by JaredCH** [comment]
Looks to happen on both ahk and exe, I'm having the same issues as Avastgard

**Comment by Avastgard** [comment]
> Thanks for the report. This happens only with the executable of the release versions or also when running [GPT3-AHK.ahk](https://github.com/htadashi/GPT3-AHK/blob/main/GPT3-AHK.ahk)?

I use the .ask version only and it shows the same issue.

**Comment by htadashi** [comment]
Dear all, thanks for reporting this issue. Unfortunately, I couldn't reproduce it on my computer, even after reinstalling AHK.

Could you try these steps to see if it can solve the problem? 

1. Check if there exist a `settings.ini` file in the same folder of GPT3-AHK.ahk (or GPT3-AHK.exe)
1. Check if `settings.ini` is correctly formated, i.e. is in the format:
    ```
    [OpenAI]
    API_KEY=********
    ```
1. Check if the API_KEY on `settings.ini` is still valid
1. In case the above does not work, try reinstalling AHK in your computer (in case you are using the .ahk version)

**Comment by Avastgard** [comment]
Tried all of your suggestions, but it none of them worked. I'm runningh ahk version 1.1.36.02.

I even generated a new API Key and edited the settings accordingly, but the problem persists. Even uninstalling and reinstalling ahk yielded no result.

**Comment by obrientatsuya** [comment]
same here.

**Comment by obrientatsuya** [comment]
the problem is probably in the http request, i found this url inside the WinHttpRequest code 0_o https://stackoverflow.com/a/59773997/11918484

**Comment by htadashi** [comment]
Thanks for reporting this issue. Unfortunately, I couldn't reproduce this error in my local machines, so PRs are appreciated in case you find a solution :)
