### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by loumizhu** [htadashi/GPT3-AHK#9]
Hello 🙌🏻

I've tested the script since weeks. And even tried to change the model used
MODEL_AUTOCOMPLETE_ID := "gpt-3.5-turbo-0301"

But after some "frequent" uses, it does not work anymore
it even get me some very out of context answers

I tried another new apikey

but seems gone completely bonker
The api status of openai seems green

Did you experience similar issues

**Comment by htadashi** [comment]
Thanks for your support @loumizhu, I really appreciate it.

Unfortunately, I couldn't reproduce the error here so I will close this issue for now. Hopefully, the new models will solve this issue.
